/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppSponsorshipRouteImport } from './routes/app.sponsorship'
import { Route as AppSponsorsRouteImport } from './routes/app.sponsors'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppLeaderboardsRouteImport } from './routes/app.leaderboards'
import { Route as AppJudgingRouteImport } from './routes/app.judging'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAccommodationRouteImport } from './routes/app.accommodation'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSponsorshipRoute = AppSponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => AppRoute,
} as any)
const AppSponsorsRoute = AppSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppJudgingRoute = AppJudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccommodationRoute = AppAccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/app/accommodation': typeof AppAccommodationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/judging': typeof AppJudgingRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/app/sponsorship': typeof AppSponsorshipRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/users': typeof AppUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/new': typeof AppEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/app/accommodation': typeof AppAccommodationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/judging': typeof AppJudgingRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/app/sponsorship': typeof AppSponsorshipRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/users': typeof AppUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/app': typeof AppIndexRoute
  '/app/events/new': typeof AppEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sponsors': typeof SponsorsRoute
  '/app/accommodation': typeof AppAccommodationRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/judging': typeof AppJudgingRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sponsors': typeof AppSponsorsRoute
  '/app/sponsorship': typeof AppSponsorshipRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/users': typeof AppUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/new': typeof AppEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/events'
    | '/login'
    | '/signup'
    | '/sponsors'
    | '/app/accommodation'
    | '/app/dashboard'
    | '/app/events'
    | '/app/judging'
    | '/app/leaderboards'
    | '/app/reports'
    | '/app/sponsors'
    | '/app/sponsorship'
    | '/app/teams'
    | '/app/users'
    | '/events/$eventId'
    | '/app/'
    | '/app/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/login'
    | '/signup'
    | '/sponsors'
    | '/app/accommodation'
    | '/app/dashboard'
    | '/app/events'
    | '/app/judging'
    | '/app/leaderboards'
    | '/app/reports'
    | '/app/sponsors'
    | '/app/sponsorship'
    | '/app/teams'
    | '/app/users'
    | '/events/$eventId'
    | '/app'
    | '/app/events/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/events'
    | '/login'
    | '/signup'
    | '/sponsors'
    | '/app/accommodation'
    | '/app/dashboard'
    | '/app/events'
    | '/app/judging'
    | '/app/leaderboards'
    | '/app/reports'
    | '/app/sponsors'
    | '/app/sponsorship'
    | '/app/teams'
    | '/app/users'
    | '/events/$eventId'
    | '/app/'
    | '/app/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sponsorship': {
      id: '/app/sponsorship'
      path: '/sponsorship'
      fullPath: '/app/sponsorship'
      preLoaderRoute: typeof AppSponsorshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sponsors': {
      id: '/app/sponsors'
      path: '/sponsors'
      fullPath: '/app/sponsors'
      preLoaderRoute: typeof AppSponsorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboards': {
      id: '/app/leaderboards'
      path: '/leaderboards'
      fullPath: '/app/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/judging': {
      id: '/app/judging'
      path: '/judging'
      fullPath: '/app/judging'
      preLoaderRoute: typeof AppJudgingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accommodation': {
      id: '/app/accommodation'
      path: '/accommodation'
      fullPath: '/app/accommodation'
      preLoaderRoute: typeof AppAccommodationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsNewRoute: typeof AppEventsNewRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsNewRoute: AppEventsNewRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppAccommodationRoute: typeof AppAccommodationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppJudgingRoute: typeof AppJudgingRoute
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSponsorsRoute: typeof AppSponsorsRoute
  AppSponsorshipRoute: typeof AppSponsorshipRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccommodationRoute: AppAccommodationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppJudgingRoute: AppJudgingRoute,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSponsorsRoute: AppSponsorsRoute,
  AppSponsorshipRoute: AppSponsorshipRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
